name: icesat2020
channels:
  - conda-forge
dependencies:
# Core pangeo jupyterhub requirements
  - python=3.8
  - pangeo-notebook=2020.04.04
  - python-graphviz
  - pip=20.0
# Additional libraries (alphabetical order)
  - astropy
  - awscli
  - cartopy
  - code-server
  - contextily
  - datashader
  - descartes
  - fiona
  - fsspec
  - gcsfs
  - gdal
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipywidgets
  - joblib
  - lxml
  - mapclassify
  - matplotlib-base
  - matplotlib-scalebar
  - mercantile
  - nb_conda_kernels
  - nomkl
  - numba
  - numpy
  - pandas
  - paramiko
  - pexpect
  - pillow
  - psutil
  - pyepsg
  - pymc3
  - pyproj
  - pyshp
  - pytest
  - rasterio
  - rasterstats
  - rio-cogeo
  - sat-search
  - sat-stac
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - supermercado
  - tensorflow
  - tqdm
  - xarray
  - yaml
  - zarr
  - pip:
    - git+https://github.com/icesat2py/icepyx.git@master
    - git+https://github.com/fspaolo/captoolkit.git@master
