# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: icesat2020
channels:
  - conda-forge
dependencies:
# Core pangeo jupyterhub requirements
  - python=3.8
  - jupyterlab=1.2
  - jupyterhub=1.1
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - dask=2.10
  - distributed=2.10
  - dask-kubernetes=0.10
  - dask-gateway=0.6
  - dask-labextension=1.1
  - tornado=6
  - bokeh=1.4
  - python-graphviz=0.13
  - pip=20.0
# Additional libraries (alphabetical order)
  - awscli=1.17
  - cartopy=0.17
  - contextily
  - datashader=0.10
  - descartes=1.1
  - fiona=1.8
  - fsspec=0.6
  - gcsfs=0.6
  - gdal=3.0
  - geopandas=0.6
  - geoviews-core=1.6
  - h5netcdf=0.8
  - h5py=2.10
  - holoviews=1.12
  - hvplot=0.5
  - intake=0.5
  - intake-xarray=0.3
  - ipykernel=5.1
  - ipyleaflet=0.12
  - ipympl=0.4
  - ipywidgets=7.5
  - joblib=0.14
  - lxml=4.5
  - mapclassify=2.2
  - matplotlib-base=3.1
  - matplotlib-scalebar=0.6
  - mercantile=1.1
  - nb_conda_kernels=2.2
  - nomkl=3.0
  - numba=0.48
  - numpy=1.18
  - pandas=1.0
  - paramiko=2.7
  - pexpect=4.8
  - pillow=7.0
  - psutil=5.6
  - pyepsg=0.4
  - pyproj
  - pyshp=2.1
  - rasterio=1.1
  - rasterstats=0.14
  - rio-cogeo=1.1
  - sat-search=0.2
  - sat-stac=0.3
  - s3fs=0.4
  - scikit-image=0.16
  - scipy=1.4
  - seaborn=0.10
  - shapely=1.7
  - statsmodels=0.11
  - supermercado=0.0.5
  - xarray=0.15
  - zarr=2.4
#  - pip:
#    - git+https://github.com/icesat2py/icepyx.git@2a0fc77ca135d9e41448f1afd82d5c2038ec9bce
