# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: icesat2020
channels:
  - conda-forge
dependencies:
# Core pangeo jupyterhub requirements
  - python=3.8
  - pangeo-notebook=2020.04.03
  - python-graphviz
  - pip=20.0
# Additional libraries (alphabetical order)
  - awscli
  - cartopy
  - contextily
  - datashader
  - descartes
  - fiona
  - fsspec
  - gcsfs
  - gdal
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipywidgets
  - joblib
  - lxml
  - mapclassify
  - matplotlib-base
  - matplotlib-scalebar
  - mercantile
  - nb_conda_kernels
  - nomkl
  - numba
  - numpy
  - pandas
  - paramiko
  - pexpect
  - pillow
  - psutil
  - pyepsg
  - pyproj
  - pyshp
  - rasterio
  - rasterstats
  - rio-cogeo
  - sat-search
  - sat-stac
  - s3fs
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - supermercado
  - xarray
  - yaml
  - zarr
#  - pip:
#    - git+https://github.com/icesat2py/icepyx.git@2a0fc77ca135d9e41448f1afd82d5c2038ec9bce
#    - git+https://github.com/fspaolo/captoolkit.git@03bb4e01790451e557dc91a8e5a11e898e0b7fc9
