# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: icesat2020
channels:
  - conda-forge
dependencies:
# Core pangeo jupyterhub requirements
  - python=3.8
  - jupyterlab=1.2
  - jupyterhub=1.1
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - dask=2.10
  - distributed=2.10
  - dask-kubernetes=0.10
  - dask-gateway=0.6
  - dask-labextension=1.1
  - tornado=6
  - bokeh=1.4
  - python-graphviz=0.13
  - pip=20.0
# Additional libraries (alphabetical order)
  - awscli
  - cartopy
  - contextily
  - datashader
  - descartes
  - fiona
  - gcsfs
  - gdal
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipywidgets
  - joblib
  - lxml
  - mapclassify
  - matplotlib-core
  - matplotlib-scalebar
  - mercantile
  - nb_conda_kernels
  - nomkl
  - numba
  - numpy
  - pandas
  - paramiko
  - pexpect
  - pillow
  - psutil
  - pyepsg
  - pyproj
  - pyshp
  - rasterio
  - rasterstats
  - rio-cogeo
  - sat-search
  - sat-stac
  - s3fs
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - supermercado
  - xarray
  - yaml
  - zarr
  - pip:
    - git+https://github.com/icesat2py/icepyx.git@2a0fc77ca135d9e41448f1afd82d5c2038ec9bce
