#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install --clean @jupyter-widgets/jupyterlab-manager \
                                      @pyviz/jupyterlab_pyviz \
                                      jupyter-matplotlib \
                                      jupyter-leaflet \
                                      dask-labextension

# --clean is not getting everything (this reduces image size)
rm -rf ${HOME}/.cache ${HOME}/.npm ${HOME}/.yarn
rm -rf ${KERNEL_PYTHON_PREFIX}/share/jupyter/lab/staging
find ${KERNEL_PYTHON_PREFIX} -follow -type f -name '*.js.map' -delete

# dask config
# ${KERNEL_PYTHON_PREFIX} is set by repo2docker to sys.prefix
# of the python that the kernel is run in.
mkdir -p ${KERNEL_PYTHON_PREFIX}/etc/dask
cp binder/dask_config.yaml ${KERNEL_PYTHON_PREFIX}/etc/dask/dask.yaml
