#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install --clean @jupyter-widgets/jupyterlab-manager \
                                      @pyviz/jupyterlab_pyviz \
                                      jupyter-matplotlib \
                                      jupyter-leaflet \
                                      dask-labextension

# EOF
