name: MasterBuild

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - 'README.md'

env:
  CONTAINER_NAME: uwhackweeks/icesat2
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${CONTAINER_NAME}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"

    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{ env.CONTAINER_NAME }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest, ${{env.DOCKER_TAG}}"

    - name: Export Full Conda Environment
      run: |
        docker run ${CONTAINER_NAME}:latest conda list --explicit > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt
