name: MasterBuild

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - binder/*

env:
  CONTAINER_NAME: uwhackweeks/icesat2
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    env:
      IMAGE: base-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${CONTAINER_NAME}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"

    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${env.CONTAINER_NAME}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: binder
        tags: "latest, ${{env.DOCKER_TAG}}"
