name: PullRequestBuild

on:
  pull_request:
    branches:
      - master
    paths:
      - binder/*
      - .github/workflows/*
      - requirements.txt

env:
  CONTAINER_NAME: uwhackweeks/icesat2
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Enable Pip Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt

    - name: Build Image
      run: |
        if docker pull $CONTAINER_NAME:latest; then
          jupyter-repo2docker --cache-from $CONTAINER_NAME:latest --debug --user-name jovyan --user-id 1000 --no-run --image-name $CONTAINER_NAME:latest $PWD
        else
          jupyter-repo2docker --debug --user-name jovyan --user-id 1000 --no-run --image-name $CONTAINER_NAME:latest $PWD
        fi
        docker run ${ONBUILD_IMAGE_SPEC} conda list > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt
