# Only test building images
name: PullRequestBuild

on:
  pull_request:
    branches:
      - master
    paths:
      - binder/*

env:
  CONTAINER_NAME: uwhackweeks/icesat2
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Image
      run: |
        cd ${{ matrix.IMAGE }}
        docker build -t ${CONTAINER_NAME}:PR .

    - name: Export Full Conda Environment
      run: |
        docker run ${CONTAINER_NAME}:PR conda list --explicit > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt
